# To prepare: install rabbitmq:
#   docker run -it --rm -d --name rabbitmq -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3.11-management
# Run:
# go install github.com/mattn/goreman && goreman start

consumer: go run ./hello_work.go consumer
publisher: go run ./hello_work.go publisher