// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dokiys/go_test/go/zz_my/fly/cmd"
	"github.com/Dokiys/go_test/go/zz_my/fly/conf"
	"github.com/google/wire"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func initApp(conf2 *conf.Config) (cli.Commands, func()) {
	oneCmd := cmd.NewOneCmd(conf2)
	twoCmd := cmd.NewTwoCmd(conf2)
	commands := &cmd.Commands{
		OneCmd: oneCmd,
		TwoCmd: twoCmd,
	}
	cliCommands, cleanup := cmd.NewCommands(commands)
	return cliCommands, func() {
		cleanup()
	}
}

// wire.go:

var providerSet = wire.NewSet(cmd.NewOneCmd, cmd.NewTwoCmd, cmd.NewCommands, wire.Struct(new(cmd.Commands), "*"))
