// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dokiys/go_test/go/zz_my/fly"
	"github.com/Dokiys/go_test/go/zz_my/fly/demo/conf"
	"github.com/Dokiys/go_test/go/zz_my/fly/demo/server/one"
	"github.com/Dokiys/go_test/go/zz_my/fly/demo/server/two"
)

// Injectors from wire.go:

func NewOneFly(loader fly.ConfigLoader) *one.One {
	config := conf.NewConfig(loader)
	oneOne := one.NewOne(config)
	return oneOne
}

func NewTwoFly(loader fly.ConfigLoader) *two.Two {
	config := conf.NewConfig(loader)
	twoTwo := two.NewTwo(config)
	return twoTwo
}
