// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dokiys/go_test/go/zz_my/fly/cmd"
	"github.com/Dokiys/go_test/go/zz_my/fly/cmd/temp"
	"github.com/Dokiys/go_test/go/zz_my/fly/conf"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func initApp() cli.Commands {
	config := conf.InitConf()
	oneCmd := cmd.NewOneCmd(config)
	twoCmd := cmd.NewTwoCmd(config)
	subOneCmd := temp.NewSubOneCmd(config)
	subTwoCmd := temp.NewSubTwoCmd(config)
	tempTemp := &temp.Temp{
		SubOneCmd: subOneCmd,
		SubTwoCmd: subTwoCmd,
	}
	tempCmd := temp.NewTempCmd(tempTemp)
	commands := &cmd.Commands{
		OneCmd:  oneCmd,
		TwoCmd:  twoCmd,
		TempCmd: tempCmd,
	}
	cliCommands := cmd.NewCommands(commands)
	return cliCommands
}
