// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package temp

import (
	"github.com/Dokiys/go_test/go/zz_my/fly"
	"github.com/Dokiys/go_test/go/zz_my/fly/demo/conf"
)

// Injectors from wire.go:

func NewSubOneFly(loader fly.ConfigLoader) *SubOne {
	config := conf.NewConfig(loader)
	subOne := NewSubOne(config)
	return subOne
}

func NewSubTwoFly(loader fly.ConfigLoader) *SubTwo {
	config := conf.NewConfig(loader)
	subTwo := NewSubTwo(config)
	return subTwo
}
