# Run:
# go install github.com/mattn/goreman && goreman start

consumer1: go run ./pub_sub.go consumer "zhangsan"
consumer2: go run ./pub_sub.go consumer "lisi"
publisher: go run ./pub_sub.go publisher "Hello"