#!/usr/bin/env bash

############### /初始化 .zshrc 配置文件/ ###############
# 检查是否存在
find ~/.zshrc2 > /dev/null 2>&1
if [ $? -ne 0 ]; then
  touch ~/.zshrc
fi

echo "" >> ~/.zshrc
echo "" >> ~/.zshrc
echo "# ========== [Dokiy] ==========" >> ~/.zshrc
echo "# Generated by shell job. DO NOT EDIT." >> ~/.zshrc
echo "# ============ END ============" >> ~/.zshrc
######################################################

# TODO[Dokiy]: zsh 打开iterm
