# To prepare: install rabbitmq:
#   docker run -it --rm -d --name rabbitmq -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3.11-management
# Run:
# go install github.com/mattn/goreman && goreman start

consumer1: go run ./pub_sub.go consumer "zhangsan"
consumer2: go run ./pub_sub.go consumer "lisi"
publisher: go run ./pub_sub.go publisher "Hello"