#!/bin/sh

# Check DELETE ME
zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
while read local_ref local_oid remote_ref remote_oid; do
  if test "$local_oid" = "$zero"; then
    # Handle delete
    :
  else
    if test "$remote_oid" = "$zero"; then
      # New branch, examine all commits
      range="$local_oid"
      deleteme_range="$(git --no-pager reflog $local_ref | tail -n 1 | awk '{print $1}')"
    else
      # Update to existing branch, examine new commits
      range="$remote_oid..$local_oid"
      deleteme_range="$remote_oid..$local_oid"
    fi

    deleteme=$(git --no-pager diff $deleteme_range | grep '+' | grep '// TODO' | grep 'DELETE ME')
    if [ ! -z "$deleteme" ]; then
      echo >&2 "Found [DELETE ME] in commit, not pushing"
      echo >&2 "  (use \"git push -no-verify\" to discard)"
      exit 2
    fi
  fi
done

# Check lint
if [ ! -e .golangci.yml ] || ! command -v golangci-lint >/dev/null; then
  exit 0
fi

golangci-lint run 1>&2
if [ $? -ne 0 ]; then
  echo 1>&2 "  (use \"git push -no-verify\" to discard)";
  exit 2;
fi

exit 0