#!/bin/sh

# check lint
if [ ! -e .golangci.yml ] || ! command -v golangci-lint >/dev/null; then
  exit 0
fi

golangci-lint run 1>&2

if [ $? -ne 0 ]; then
  echo 1>&2 "  (use \"git push -no-verify\" to discard)";
  exit 2;
fi