#!/bin/sh

MAX_SIZE=$((1024 * 1024 * 1))
FILES=$(git --no-pager diff --cached --name-status | awk '$1=="M" || $1=="A" {$1="";print}')

for file in $FILES; do
  size=$(ls -la "$file" | awk '{print $5}')

  if [ $size -gt $MAX_SIZE ]; then
    ERR_FILES[${#ERR_FILES[@]}]=$file
    continue
  fi
done

if [ ${#ERR_FILES[@]} -eq 0 ]; then
  exit 0
fi

# Regular Colors
Red='\033[0;31m' # Red
ERR="Exceed max size files:\n  (use \"git commit --no-verify -m 'COMMENT'\" to discard)"
for E_FILE in $ERR_FILES; do
  echo 1>&2 "${ERR}\n${Red}${E_FILE}"
done

exit 1