# Run:
# go install github.com/mattn/goreman && goreman start

*.orange.*: go run ./topic.go consumer *.orange.*
*.*.rabbit: go run ./topic.go consumer *.*.rabbit
lazy.#: go run ./topic.go consumer lazy.#
publisher: go run ./topic.go publisher lazy.orange.rabbit "Hello"